nodeLinker: node-modules

packageExtensions:
  "eslint-plugin-import@2.31.0":
    peerDependencies:
      eslint: ">=10"
  "eslint-plugin-react@7.37.4":
    peerDependencies:
      eslint: ">=10"
  "eslint-plugin-jsx-a11y@6.10.2":
    peerDependencies:
      eslint: ">=10"
  "eslint-plugin-react-hooks@5.2.0":
    peerDependencies:
      eslint: ">=10"
