name: Publish

on:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - 'main'

jobs:
  versioning:
    uses: GEWIS/actions/.github/workflows/versioning.yml@v1
    with:
      dry-run: 'true'

  publish-npm:
    uses: GEWIS/actions/.github/workflows/npm-release.yml@v1
    needs: versioning
    if: ${{ needs.versioning.outputs.next-version != '' }}
    with:
      node-version: '22.x'
      version: ${{ needs.versioning.outputs.next-version }}
      lerna: 'true'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
